### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by PaulWaldo** [tj-actions/coverage-badge-go#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The below script works properly, creating a commit with updated coverage info in README.md.  The problem is that the Pull Request is not able to be merged because the badge commit is not signed: 
```
Merging is blocked
The base branch requires all commits to be signed.
```
### My `coverage_badge.yml`
```
# https://github.com/tj-actions/coverage-badge-go
name: "Coverage Badge"
on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    name: Update coverage badge
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Install OS dependencies
        run: sudo apt-get update && sudo apt-get install libgl1-mesa-dev xorg-dev

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Test
        run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out

      - name: Go Coverage Badge # Pass the `coverage.out` output to this action
        uses: tj-actions/coverage-badge-go@v2
        with:
          filename: coverage.out

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v9.1
        id: verify-changed-files
        with:
          files: README.md

      - name: Commit changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "chore: Updated coverage badge."

      - name: Push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.head_ref }}
```

### To Reproduce

1. Add above script to project and commit
2. Create a PR on a branch that requires commits to be signed
3. Observe that GitHub will not allow the PR to be merged

### What OS are you seeing the problem on?

macos-latest or macos-10.15

### Expected behavior?

I expected the commit to be signed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
